name: cpsc381-ufc
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.3.7
  - ca-certificates=2024.3.11
  - colorama=0.4.6
  - comm=0.2.2
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - icc_rt=2022.1.0
  - importlib-metadata=7.0.2
  - importlib_metadata=7.0.2
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.18.1
  - jedi=0.19.1
  - joblib=1.2.0
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - libsodium=1.0.18
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.2.1
  - packaging=24.0
  - pandas=2.2.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.0
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3.post1
  - pywin32=306
  - pyzmq=25.1.2
  - scikit-learn=1.4.1.post1
  - scipy=1.11.4
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tornado=6.4
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - vc=14.2
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - wheel=0.41.2
  - zeromq=4.3.5
  - zipp=3.17.0
  - pip:
      - clarabel==0.7.1
      - cvxpy==1.4.2
      - ecos==2.0.13
      - osqp==0.6.5
      - pybind11==2.11.1
      - qdldl==0.1.7.post0
      - scs==3.2.4.post1
