name: cpsc381-ufc
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.0
  - cycler=0.11.0
  - debugpy=1.8.1
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - icc_rt=2022.1.0
  - icu=73.1
  - importlib-metadata=7.0.2
  - importlib_metadata=7.0.2
  - importlib_resources=6.1.1
  - intel-openmp=2023.1.0
  - ipykernel=6.29.3
  - ipython=8.18.1
  - jedi=0.19.1
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.1
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
  - libffi=3.4.2
  - libhwloc=2.9.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libpng=1.6.39
  - libpq=12.17
  - libsodium=1.0.18
  - libsqlite=3.45.2
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib=2.2.5
  - matplotlib-base=2.2.5
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.2.1
  - packaging=24.0
  - pandas=2.2.1
  - parso=0.8.3
  - pickleshare=0.7.5
  - pip=23.3.1
  - platformdirs=4.2.0
  - ply=3.11
  - prompt-toolkit=3.0.42
  - psutil=5.9.8
  - pthreads-win32=2.9.1
  - pure_eval=0.2.2
  - pygments=2.17.2
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3.post1
  - pywin32=306
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - scikit-learn=1.4.1.post1
  - scipy=1.11.4
  - setuptools=68.2.2
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - threadpoolctl=2.2.0
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.4
  - traitlets=5.14.2
  - typing_extensions=4.10.0
  - tzdata=2024a
  - ucrt=10.0.22621.0
  - vc=14.2
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wcwidth=0.2.13
  - wheel=0.41.2
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - clarabel==0.7.1
      - cvxpy==1.4.2
      - ecos==2.0.13
      - osqp==0.6.5
      - pillow==10.2.0
      - pybind11==2.11.1
      - qdldl==0.1.7.post0
      - scs==3.2.4.post1
