# super hacky, for some reason SQLite slows to a crawl when inner joining with the following query


SHERDOG_STREAKS_QUERY = """
WITH sherdog_streak_ids AS (
  SELECT 
    t2.UFCSTATS_FIGHTER_ID, 
    t1.EVENT_ID, 
    t1.FIGHTER_BOUT_ORDINAL, 
    t1.OUTCOME, 
    (
      (t1.FIGHTER_BOUT_ORDINAL + 1) - ROW_NUMBER() OVER (
        PARTITION BY t1.FIGHTER_ID, 
        t1.OUTCOME 
        ORDER BY 
          t1.FIGHTER_BOUT_ORDINAL
      )
    ) AS rn_diff 
  FROM 
    sherdog.SHERDOG_BOUT_HISTORY AS t1
    INNER JOIN sherdog.SHERDOG_FIGHTER_LINKAGE AS t2 ON t1.FIGHTER_ID = t2.SHERDOG_FIGHTER_ID
),
sherdog_streaks AS (
  SELECT 
    UFCSTATS_FIGHTER_ID, 
    EVENT_ID, 
    FIGHTER_BOUT_ORDINAL, 
    OUTCOME, 
    ROW_NUMBER() OVER (
      PARTITION BY UFCSTATS_FIGHTER_ID, 
      rn_diff 
      ORDER BY 
        FIGHTER_BOUT_ORDINAL
    ) AS streak 
  FROM 
    sherdog_streak_ids
), 
sherdog_win_lose_streaks AS (
  SELECT 
    UFCSTATS_FIGHTER_ID, 
    EVENT_ID, 
    FIGHTER_BOUT_ORDINAL, 
    OUTCOME, 
    CASE WHEN OUTCOME = 'W' THEN streak ELSE 0 END AS WINNING_STREAK_POST, 
    CASE WHEN OUTCOME = 'L' THEN streak ELSE 0 END AS LOSING_STREAK_POST 
  FROM 
    sherdog_streaks
), 
sherdog_streak_features AS (
  SELECT 
    UFCSTATS_FIGHTER_ID, 
    EVENT_ID, 
    FIGHTER_BOUT_ORDINAL, 
    LAG(WINNING_STREAK_POST, 1) OVER (
      PARTITION BY UFCSTATS_FIGHTER_ID 
      ORDER BY 
        FIGHTER_BOUT_ORDINAL
    ) AS WINNING_STREAK, 
    LAG(LOSING_STREAK_POST, 1) OVER (
      PARTITION BY UFCSTATS_FIGHTER_ID 
      ORDER BY 
        FIGHTER_BOUT_ORDINAL
    ) AS LOSING_STREAK, 
    AVG(WINNING_STREAK_POST) OVER (
      PARTITION BY UFCSTATS_FIGHTER_ID  
      ORDER BY 
        FIGHTER_BOUT_ORDINAL ROWS BETWEEN UNBOUNDED PRECEDING 
        AND 1 PRECEDING
    ) AS WINNING_STREAK_AVERAGE, 
    AVG(LOSING_STREAK_POST) OVER (
      PARTITION BY UFCSTATS_FIGHTER_ID  
      ORDER BY 
        FIGHTER_BOUT_ORDINAL ROWS BETWEEN UNBOUNDED PRECEDING 
        AND 1 PRECEDING
    ) AS LOSING_STREAK_AVERAGE, 
    MAX(WINNING_STREAK_POST) OVER (
      PARTITION BY UFCSTATS_FIGHTER_ID  
      ORDER BY 
        FIGHTER_BOUT_ORDINAL ROWS BETWEEN UNBOUNDED PRECEDING 
        AND 1 PRECEDING
    ) AS WINNING_STREAK_MAX, 
    MAX(LOSING_STREAK_POST) OVER (
      PARTITION BY UFCSTATS_FIGHTER_ID  
      ORDER BY 
        FIGHTER_BOUT_ORDINAL ROWS BETWEEN UNBOUNDED PRECEDING 
        AND 1 PRECEDING
    ) AS LOSING_STREAK_MAX 
  FROM 
    sherdog_win_lose_streaks
), 
sherdog_streak_features_filtered AS (
  SELECT 
    *, 
    ROW_NUMBER() OVER (
      PARTITION BY UFCSTATS_FIGHTER_ID  
      ORDER BY 
        FIGHTER_BOUT_ORDINAL
    ) AS FIGHTER_BOUT_NUMBER 
  FROM 
    sherdog_streak_features 
  WHERE 
    EVENT_ID IN (
      SELECT 
        EVENT_ID 
      FROM 
        sherdog.SHERDOG_BOUTS
    )
)

SELECT
  *
FROM
  sherdog_streak_features_filtered;
"""

NUM_BOUTS_BY_FIGHTER_QUERY = """
WITH bout_num_by_fighter AS (
  SELECT 
    *, 
    ROW_NUMBER() OVER(
      PARTITION BY FIGHTER_ID 
      ORDER BY 
        DATE, 
        EVENT_ID, 
        BOUT_ORDINAL
    ) AS FIGHTER_BOUT_NUMBER 
  FROM 
    (
      SELECT 
        BOUT_ID, 
        EVENT_ID, 
        DATE, 
        BOUT_ORDINAL, 
        RED_FIGHTER_ID AS FIGHTER_ID 
      FROM 
        main.UFCSTATS_BOUTS_OVERALL 
      UNION ALL 
      SELECT 
        BOUT_ID, 
        EVENT_ID, 
        DATE, 
        BOUT_ORDINAL, 
        BLUE_FIGHTER_ID AS FIGHTER_ID 
      FROM 
        main.UFCSTATS_BOUTS_OVERALL
    ) 
)

SELECT
  *
FROM
  bout_num_by_fighter;
"""
