-- Reach, height, and elevation features
WITH elevations_raw AS (
  SELECT 
    *, 
    ROW_NUMBER() OVER(
      PARTITION BY FIGHTER_ID 
      ORDER BY 
        DATE, 
        EVENT_ID, 
        BOUT_ORDINAL
    ) AS FIGHTER_BOUT_NUMBER 
  FROM 
    (
      SELECT 
        t1.BOUT_ID, 
        t1.EVENT_ID, 
        t1.DATE, 
        t1.BOUT_ORDINAL, 
        t1.RED_FIGHTER_ID AS FIGHTER_ID, 
        t2.ELEVATION_METERS 
      FROM 
        main.UFCSTATS_BOUTS_OVERALL AS t1 
        INNER JOIN main.LOCATION_ELEVATIONS AS t2 ON t1.LOCATION = t2.LOCATION 
      UNION ALL 
      SELECT 
        t1.BOUT_ID, 
        t1.EVENT_ID, 
        t1.DATE, 
        t1.BOUT_ORDINAL, 
        t1.BLUE_FIGHTER_ID AS FIGHTER_ID, 
        t2.ELEVATION_METERS 
      FROM 
        main.UFCSTATS_BOUTS_OVERALL AS t1 
        INNER JOIN main.LOCATION_ELEVATIONS AS t2 ON t1.LOCATION = t2.LOCATION
    )
), 
elevation_features AS (
  SELECT 
    BOUT_ID, 
    FIGHTER_ID, 
    FIGHTER_BOUT_NUMBER, 
    AVG(ELEVATION_METERS) OVER(
      PARTITION BY FIGHTER_ID 
      ORDER BY 
        FIGHTER_BOUT_NUMBER ROWS BETWEEN UNBOUNDED PRECEDING 
        AND 1 PRECEDING
    ) AS ELEVATION_METERS_AVERAGE, 
    MAX(ELEVATION_METERS) OVER(
      PARTITION BY FIGHTER_ID 
      ORDER BY 
        FIGHTER_BOUT_NUMBER ROWS BETWEEN UNBOUNDED PRECEDING 
        AND 1 PRECEDING
    ) AS ELEVATION_METERS_MAX 
  FROM 
    elevations_raw
) 
SELECT 
  t1.BOUT_ID, 
  t1.EVENT_ID, 
  t1.DATE, 
  t1.BOUT_ORDINAL, 
  CASE WHEN t2.REACH_INCHES - t3.REACH_INCHES IS NULL THEN 0 ELSE t2.REACH_INCHES - t3.REACH_INCHES END AS UFCSTATS_REACH_INCHES_DIFF, 
  CASE WHEN CAST(t2.REACH_INCHES AS FLOAT) / t3.REACH_INCHES IS NULL THEN 1 ELSE CAST(t2.REACH_INCHES AS FLOAT) / t3.REACH_INCHES END AS UFCSTATS_REACH_INCHES_RATIO, 
  t4.ELEVATION_METERS_AVERAGE - t5.ELEVATION_METERS_AVERAGE AS UFCSTATS_ELEVATION_METERS_AVERAGE_DIFF, 
  CAST(t4.ELEVATION_METERS_MAX AS FLOAT) / t5.ELEVATION_METERS_MAX AS UFCSTATS_ELEVATION_METERS_MAX_RATIO, 
  CASE t1.RED_OUTCOME WHEN 'W' THEN 1 WHEN 'L' THEN 0 ELSE NULL END AS RED_WIN 
FROM 
  main.UFCSTATS_BOUTS_OVERALL AS t1 
  INNER JOIN main.UFCSTATS_FIGHTERS AS t2 ON t1.RED_FIGHTER_ID = t2.FIGHTER_ID 
  INNER JOIN main.UFCSTATS_FIGHTERS AS t3 ON t1.BLUE_FIGHTER_ID = t3.FIGHTER_ID 
  INNER JOIN elevation_features AS t4 ON t1.BOUT_ID = t4.BOUT_ID 
  AND t1.RED_FIGHTER_ID = t4.FIGHTER_ID 
  INNER JOIN elevation_features AS t5 ON t1.BOUT_ID = t5.BOUT_ID 
  AND t1.BLUE_FIGHTER_ID = t5.FIGHTER_ID 
WHERE 
  t4.FIGHTER_BOUT_NUMBER > 1 
  AND t5.FIGHTER_BOUT_NUMBER > 1 
  AND t1.DATE > ? 
ORDER BY 
  t1.DATE, 
  t1.EVENT_ID, 
  t1.BOUT_ORDINAL;


-- Striking and grappling features